package com.BDD.GoAudits;

public class Locators {
	
	public enum Locator {
		CLASSNAME,CSSSELECTOR,ID,LINKTEXT,NAME,PARTIALLINKTEXT,XPATH,TAGNAME
	}
	
	public enum Selector {
		SELECTBYVISIBLTTEXT,SELECTBYVALUE,SELECTBYINDEX,
		DESELECTALL,DESELECTBYVISIBLTTEXT,DESELECTBYVALUE,DESELECTBYINDEX
	}
	
	
}
